name: Build docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: "Build Docker Image"
        required: true

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "wave-league"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          branch: "master"
          healthcheck: "https://wave-league.herokuapp.com"
